### ISSUE TITLE
Who is using cleanwhite？(谁在使用 cleanwhite？)

### ISSUE THREAD

**Issue by zhaohuabing** [zhaohuabing/hugo-theme-cleanwhite#115]
## Who is using cleanwhite？

Sincerely thank everyone who constantly keeps on using and supporting cleanwhite. We expect you to submit a comment on this issue to include the following information:

your blog's name.
your blog's address.
your blog's public repo (if there's any).
your contact info: blog, email, twitter (at least one).

You can refer to the following sample answer:

```yaml
Blog Name: Huabing Blog
Blog Addr: https://zhaohuabing.com
Blog Repo: https://github.com/zhaohuabing/hugo_blog
Contact: zhaohuabing@gmail.com https://twitter.com/zhaohuabing
```

## 谁在使用 cleanwhite？

感谢正在使用和关注 cleanwhite 的爱好者，我们期待您在此提交一条评论, 评论内容包括:

您博客的名称
您博客的地址
您使用到 cleanwhite 的公共仓库（如果有的话）
您的联系方式: 微博、邮箱、微信 (至少一个)

可以参考下面的示例：

```yaml
博客名称：Huabing Blog
博客地址：https://zhaohuabing.com
公共仓库：https://github.com/zhaohuabing/hugo_blog
联系方式：zhaohuabing@gmail.com https://twitter.com/zhaohuabing
```
