### ISSUE TITLE
Changing home to About instead of All Posts

### ISSUE THREAD

**Issue by adrianauscanga** [zhaohuabing/hugo-theme-cleanwhite#153]
Hi! Thank you for creating this theme. I'm using your theme for my personal website. I would like the home page to be my About page instead of my blog Posts but I can't find where to change that. I was wondering if it's possible to modify that and if so, would you point me to the right direction?
Thank you very much!

Adriana

**Comment by zhaohuabing** [comment]
You want "about" page link to the home page? 

You can change the link in the config.yaml like this:

```
  addtional_menus:
    - title: READING
      href: /reading/
    - title: PHOTOS
      href: /photos/
    - title: NOTES
      href: /notes/
    - title: ARCHIVE
      href: /archive/
    - title: ABOUT
      href: https://zhaohuabing.com #change this to your home page
```
