### ISSUE TITLE
How to control size paddin in header

### ISSUE THREAD

**Issue by marcinpraczko** [zhaohuabing/hugo-theme-cleanwhite#54]
Hi, 

First of all thank you for simple and nice theme to hugo. I just started use it and first challenge is space for image in header. For my purpose I would like to have lower height for image and header / subheader. I am not web-developer - however as I can see `<header>` is having (on my script) hard-coded height (1910x398). How I can change height to be lower? 

I would like to have space decrease by 2 for example (still able add some picture in background) but not have so much space consumed by header? 

Could you advice how I can achieve this, please? 

One more time - thank you for great theme.

**Comment by marcinpraczko** [comment]
OK - so I think I really sorted this. So sharing solution which did work for me:

1. Create custom CSS in hugo page project: `static/css/hux-blog.min-custom.css`
2. Copy `head.html` from theme folder into hugo page project `layouts/partials/head.html`
3. Adjust `head.html` with custom CSS

```html
<!-- Custom CSS -->
<link rel="stylesheet" href="{{ "css/hux-blog.min.css" | relURL }}">
<link rel="stylesheet" href="{{ "css/hux-blog.min-custom.css" | relURL }}">
```
And this is result of `css/hux-blog.min-custom.css`
```css
/* NOTE: Not overwrite color yet - but thinking about it */
.intro-header {
 background-color:gray;
}

@media only screen and (min-width:768px) {
 .intro-header .site-heading,
 .intro-header .post-heading,
 .intro-header .page-heading {
  padding:8% 0
 }
}
```
In my case I needed to adjust this `padding` -> into 8%, this is what I was looking for.
I have hope that this may help you as well.
