### ISSUE TITLE
Changing the colour of header text

### ISSUE THREAD

**Issue by jayhorton** [zhaohuabing/hugo-theme-cleanwhite#89]
Hi Huabing,
Your cleanwhite template is awesome. I would like to change the colour of all text that appears in the header from white to hex color #f8ae00 - blog title, the menu text, and the post titles, subtitles and date.
Please advise on how I should do this; perhaps with an additional css file in /static/css/ ?
Best regards,
Jay

**Comment by zhaohuabing** [comment]
Hi Jay,

This theme does support customized css.  For example, you can change the color of menu text as follows:

1. Create file "static/css/custom.css" in the directory of your blog source.
2. Past the below css into the custom.css file.

```css
@media only screen and (min-width:768px) {
	.navbar-custom .nav li a {
		color: #f8ae00;
	}
}
.navbar-default .navbar-nav>li>a {
    color: #f8ae00;
}
```

By this way, you can also change the style of other page elements as you want.
